# Generated by Django 4.0.3 on 2022-04-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
